source 'http://rubygems.org'

gem "rails", "~>2.3.9"
gem "rake"
gem "capistrano"
gem "unicorn"
gem "mysql"
gem "bluecloth"
gem "gravtastic"
gem "thinking-sphinx", :require => "thinking_sphinx"
gem "will_paginate", "~>2.3.12"
gem "ochko-flow_pagination", "1.2.3", :require => "flow_pagination"
gem "scrooge", :git => "git://github.com/methodmissing/scrooge.git"
gem "authlogic"
gem "authlogic-oid", :require => "authlogic_openid"
gem "ruby-openid", :require => "openid"
gem "rack-openid", :require => "rack/openid"
gem "haml"
gem "delayed_job", "~>2.0.4"
gem "twitter"
