source 'http://rubygems.org'

gem 'rake', '>= 0.9.2'
gem 'rails', '~>3.2'
gem 'capistrano'
gem 'mysql'
gem 'bluecloth'
gem 'gravtastic'
gem 'thinking-sphinx', '~>3.0.2'
gem 'will_paginate'
gem 'ochko-flow_pagination', '1.2.3', :require => 'flow_pagination'
gem 'slim_scrooge'
gem 'authlogic'
gem 'authlogic-oid', :require => 'authlogic_openid'
gem 'ruby-openid', :require => 'openid'
gem 'rack-openid', :require => 'rack/openid'
gem 'haml'
gem 'delayed_job', '~>3.0.5'
gem 'twitter'
gem 'resque'
gem 'json'
gem 'aasm'
gem 'cancan'
gem 'paperclip', '~>3.0'

