#!/usr/bin/env bash

# USER=developer
# PATH=/home/$USER/.rbenv/bin:/home/$USER/.rbenv/shims:$PATH

if [ -z $BASEDIR ]; then
  export BASEDIR=/usr/local/apps/prudge
fi

if [ -z $USER ]; then
  export USER=prudge
fi

PATH=/home/$USER/.rbenv/bin:/home/$USER/.rbenv/shims:/usr/local/bin:$PATH

bundle_exec_rake () {
  CMD="bundle exec rake $1 RAILS_ENV=${RAILS_ENV:-production}"
  cd ${BASEDIR}/current > /dev/null 2>&1 && $CMD
}

case "$1" in
  start)
      bundle_exec_rake ts:start
      ;;
  stop)
      bundle_exec_rake ts:stop
      ;;
  restart)
      bundle_exec_rake ts:restart
      ;;
  reload)
      bundle_exec_rake ts:rebuild
      ;;
  *)
      echo "Usage: sphinx {start|stop|restart|reload}" >&2
      exit 1
      ;;
esac

exit 0
