#!/usr/bin/env bash

if [ -z $BASEDIR ]; then
  export BASEDIR=/usr/local/apps/prudge
fi

if [ -z $USER ]; then
  export USER=prudge
fi

PATH=/home/$USER/.rbenv/bin:/home/$USER/.rbenv/shims:/usr/local/bin:$PATH
OPTS="-c ${BASEDIR}/current/config/unicorn.rb -E ${RAILS_ENV:-production} -D"
PID="${BASEDIR}/shared/tmp/pids/unicorn.pid"

case "$1" in
  start)
      cd ${BASEDIR}/current && bundle exec unicorn_rails ${OPTS}
      ;;
  stop)
      pkill -QUIT -F ${PID}
      ;;
  restart)
      if [ -e ${PID} ]; then
          pkill -USR2 -F ${PID}
      else
          cd ${BASEDIR}/current && bundle exec unicorn_rails ${OPTS}
      fi
      ;;
  reload)
      if [ -e ${PID} ]; then
          pkill -HUP -F ${PID}
      fi
      ;;
  *)
      echo "Usage: unicorn {start|stop|restart|reload}" >&2
      exit 1
      ;;
esac

exit 0
