#!/usr/bin/env bash

if [ -z $BASEDIR ]; then
  export BASEDIR=/usr/local/apps/prudge
fi

OPTS="-c ${BASEDIR}/current/config/unicorn.rb -E ${RAILS_ENV:-production} -D"
PID="${BASEDIR}/shared/tmp/pids/unicorn.pid"

case "$1" in
  start)
      cd ${BASEDIR}/current && bundle exec unicorn_rails ${OPTS}
      ;;
  stop)
      pkill -QUIT -F ${PID}
      ;;
  restart)
      pkill -USR2 -F ${PID}
      ;;
  reload)
      pkill -HUP -F ${PID}
      ;;
  *)
      echo "Usage: unicorn {start|stop|restart|reload}" >&2
      exit 1
      ;;
esac

exit 0
